### ISSUE TITLE
PIC 16F887 not being recognized by zeppp

### ISSUE THREAD

**Issue by Kasama** [battlecoder/zeppp#13]
Hello, first of all thanks for your work on this, it is surely a very useful resource for programming PIC micro-controllers.

I am having an issue with my setup with a PIC16F887, I followed the instructions and tried some of the examples, as well as trying to flash a `blink.hex` I compiled with the mplab ide, they fail with the error saying that it is an `Unrecognized device with ID 0x0000`.

I am pretty sure the PIC is working, as it has an older program running that works.

This is the complete output of one of the examples. Leaving out `-d 16f887` has a similar output, it just omits the line saying that the Pic device was selected.

```sh
$ java -jar zeppp-cli.jar -c /dev/ttyUSB0 -d 16f887 -ra -o full_pic_dump.hex
Opening port /dev/ttyUSB0...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.2 20220824
Pic device '16f887' selected
Detecting connected device...
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x0000
```
The `interface detected` line makes me believe that the arduino part of zeppp is working properly. Also, while trying to program, the rx/tx leds on the arduino blink, which probably means it is getting the messages from the host.

My wiring from the arduino to the PIC is below. It basically follows the pins in the table from the readme, checked against the [datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/40001291H.pdf) (mine is a 40-pin package. Pins are on page 7 of the datasheet)

![IMG_20240218_044258](https://github.com/battlecoder/zeppp/assets/1714520/ad70effc-0d59-42a8-9748-786f01ceda28)

Kinda hard to get everything in a single shot, but the wires are:
green -> arduino digital 6 -> pic RE3/MCLR/VPP
orange -> arduino digital 7 -> pic RB7/ICSPDAT
brown -> arduino digital 8 -> pic RB6/ICSPCL
gray -> arduino digital 9 -> pic RB3/AN9/PGM/C12IN2-
yellow -> arduino 5V -> pic VDD
black -> arduino GND -> pic VSS

I would love to know if you have any insights as to what's going on or how can I further debug this. Thanks again!

**Comment by battlecoder** [comment]
Hi. Have you tried connecting all VDD and VSS pins? That IC has two sets of VDD/VSS pairs; one on each side of the IC package. In my testing I always connect both sides. This might be a requirement of some specific parts and not universal advice, but ever since I started using PICs, like 20 years ago, PICs with power supply pins on both sides needed both sides to be powered to work correctly. Again; this might not be the case with ALL PICs or microcontrollers, but I know from first-hand experience that some will not work with only one side connected.

Try that if you haven't already.

Regards,

**Comment by Kasama** [comment]
That is a great bit of knowledge I wouldn't have thought of, thanks.

Unfortunately, it didn't make a difference in my case. The programmer still states that it has an `Unrecognized device with ID 0x0000`.

If you have any more tips that might help here I'm happy to hear.

Thanks again,
Regards

**Comment by battlecoder** [comment]
Sorry to hear that it didn't work.
I'm a bit curious about how is the interface being detected successfully on a Duemilanove (which should also implement the automatic reset that the Arduino Uno implements), without the wait command. Can you try adding "-wait 2000" (no quotes) after "-c /dev/ttyUSB0" ?

**Comment by Kasama** [comment]
got the same result both ways

```sh
$ java -jar zeppp-cli.jar -c /dev/ttyUSB0 -wait 2000 -ra -o test.hex
Opening port /dev/ttyUSB0...
Waiting 2000 ms ...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.2 20220824
Detecting connected device...
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x0000

$ java -jar zeppp-cli.jar -c /dev/ttyUSB0 -ra -o test.hex
Opening port /dev/ttyUSB0...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.2 20220824
Detecting connected device...
ERROR: Failed to Detect connected device. Unrecognized device with ID 0x0000
```

It's possible that the serial port works a bit differently between OSs, but it seems to be able to send the [initial command](https://github.com/battlecoder/zeppp/blob/303808936ea8a1006199b7ac4d826aff60fa18f8/ZEPPP-cli/src/main/java/com/ezv/zeppp/hardware/ZEPPP.java#L38) and get a response at least, so communication seems to be working

**Comment by battlecoder** [comment]
Yeah, and your wiring seems ok from what I can see. Do you have access to a Windows box or VM? maybe it's a problem of line ending between commands or something (CRLF issues), which is a typical linux vs windows issue. I can try on a linux box after I'm done with a couple of things here, but if you can test that before I do, that'd be helpful.

**Comment by Kasama** [comment]
alright, I dug up an old notebook that has windows on it and after waiting for many minutes of updates I ran ZEPPP on it on `COM3` (I checked the arduino port on device manager) and got the exact same result. I also tried specifiying the device with`-d 16f887` with the same result.

**Comment by Kasama** [comment]
do you know of a way I can test that the flashing on this PIC is working? I know the controller itself and ports are, because it was working in an application for a few years and I'm looking into this project cuz I lost the programmer I last used and wanted to update it for a new use case.

**Comment by Kasama** [comment]
I tried some commands on the arduino ide serial console and got the following results. It seems that the `PMR` command is not returning anything.

I see that both `LVP` and `EXT` don't get any confirmation from the PIC and just returns `OK`.

I tried a `PMR` with `0x20`, which [seems to be to read the PGM memory](https://github.com/battlecoder/zeppp/blob/303808936ea8a1006199b7ac4d826aff60fa18f8/ZEPPP-cli/src/main/java/com/ezv/zeppp/ZEPPPClient.java#L193) and it also returns nothing.

I dug a bit but didn't find a good command that I can send to check if the PIC is responding.

```sh
> FWI
OK: ZEPPP 1.0.2 20220824
> PMR 0x1
OK: 
> FWI
OK: ZEPPP 1.0.2 20220824
> LVP
OK: Entering LVP Programming Mode (Legacy method)
> PMR 0x20
OK: 
> EXT
OK: Exiting LVP Programming Mode
```

**Comment by battlecoder** [comment]
Sorry it took me a while to reply back, I was gathering some components to replicate your setup. I got an Arduino Diecimila (which is the closest I have to a Duemilanove, and they are listed under the same setting on the Arduino IDE), a 16F887, breadboard and wires. I downloaded the jar and firmware from the repo (to avoid using any local version that might be different), and set up everything on the breadboard like you did.

So, a couple of things worth noticing:
1.- Without applying power to both sides of the PIC, I also got the "unrecognized device" with id 0x0000. This normally indicates that the PIC is not responding to the identification command, which also makes it quite likely that it will not respond to anything else (that seems to be what you are experiencing with the empty PMR read).
2.- I had to add the -wait command. Maybe this is due to the difference in the arduino I'm using, or a difference in the operating system. I don't think this is important; as long as you got the interface to reply like you did, this shouldn't make any difference.
3.- With the wait added, and connecting both sets of VDD/VSS it worked well for me.

It would be great if you can either try a different PIC with ZEPPP or try the PIC with a different programmer.
I suspect that your PIC is either dead, OR maybe when it was programmed someone disabled LVP (Low-voltage programming). When you program a PIC with HVP (High Voltage Programming) you have the option to disable LVP. If you do, you won't be able to program the device in LVP mode unless you enable that capability again (which can only be done with an HVP programmer).

**Comment by Kasama** [comment]
Thanks a lot for replicating the setup, that basically confirms it's a problem on my end hahaha.

I didn't know it was a thing, but it is possible that LVP got disabled last time I programmed it (honestly don't remember, it's been a while). Last time I programmed it it was certainly using the HVP method, cuz I remember some warnings about the 13V line going to MCLR.

Once again, thanks for taking the time to help me with this. I'll try to get my hands on an HVP programmer (or make one with an arduino using some other project).

Great work on this project btw, if I can reprogram the pic, I will certainly use zeppp in the future, as the board I have the PIC living normally has ICSP headers and it will be easy to setup.

Have a great one! I will close this as it doesn't seem to be a problem with zeppp itself :smile:

**Comment by battlecoder** [comment]
No problem.
I wish you the best, and thanks for your kinds words.
I hope you can use ZEPPP in a future. PICs are incredibly fun!

**Comment by vido89** [comment]
I can confirm it runs on Linux Mint I have 16F887 only issue is 

`ERROR: Memory address 0x4010 is not mapped to any memory space in the selected device (16f887)`

I use MPLAB IDE v8.92 and I have a book for my PIC in which they use MPLAB Tools 7.60 need to test to
compile my code with it to see will error remain 

Here is log

```
$ java -jar zeppp-cli.jar -ignore-bounds-error -c /dev/ttyACM0 -i PROBA1.hex  -p
Opening port /dev/ttyACM0...
Connecting to ZEPPP interface...
-- Interface detected: ZEPPP 1.0.2 20220824
Detecting connected device...
-- Device Name:     16f887
-- Device ID:       0x0104
-- Device Revision: 0x0005
Reading input Hex file: PROBA1.hex
WARNING: Memory address 0x4010 is not mapped to any memory space in the selected device (16f887)
Erasing CHIP Memory...
Writing User IDs...
Verifying User IDs...
User ID Verification finished successfully.
Writing PGM Memory...
Verifying PGM Memory...
PGM Memory Verification finished successfully.
Writing Data Memory...
Verifying Data Memory...
EEPROM Verification finished successfully.
Writing Config Words...
Verifying Config Words...
Config Word Verification finished successfully.
That took 3442 ms
```

**Comment by battlecoder** [comment]
> WARNING: Memory address 0x4010 is not mapped to any memory space in the selected device (16f887)

That is just a warning. For reasons unknown to me, some compilers/assemblers will write a lot more "data" in the output HEX file than needed, far beyond the actual physical memory of the specific PIC that you are using.

Now, in every case that I've seen, the "extra" data is just empty blocks. And I assume this happens a lot more than I originally thought it would. A lot of other PIC programmer Kits just silently ignore this (I've tried a few, and they just ignore anything outside the boundaries) but I've chosen to warn the user in case there was something wrong in their tool-chain or config.

At any rate, if the programming and verification works then you should be fine. 

Edit: Also; Thanks for reporting that it works in Linux Mint!

**Comment by vido89** [comment]
I forgot to tell you big THANKS for developing this awesome peace of software!

> > WARNING: Memory address 0x4010 is not mapped to any memory space in the selected device (16f887)
> 
> That is just a warning. For reasons unknown to me, some compilers/assemblers will write a lot more "data" in the output HEX file than needed, far beyond the actual physical memory of the specific PIC that you are using.

But without  `-ignore-bounds-error ` it's an error not warning and as you know it prevents actual flashing so that flag is mandatory for me

> 
> Now, in every case that I've seen, the "extra" data is just empty blocks. And I assume this happens a lot more than I originally thought it would. A lot of other PIC programmer Kits just silently ignore this (I've tried a few, and they just ignore anything outside the boundaries) but I've chosen to warn the user in case there was something wrong in their tool-chain or config.

OK good to know because now we know that you did it thoroughly

> At any rate, if the programming and verification works then you should be fine.
> 
> Edit: Also; Thanks for reporting that it works in Linux Mint!

This is not my first attempt to flash my PIC I tried [this one](https://github.com/Ho-Ro/ArdPicProg/issues/8) in LVP and HVP but could not flash it. And I noticed that that one does not use RB3 so what's wrong with it I have no idea

Edit: Can ZEPPP flash in HVP ?

**Comment by battlecoder** [comment]
> I forgot to tell you big THANKS for developing this awesome peace of software!
Thank *you* for using it. It always makes me happy to see new users


> But without `-ignore-bounds-error ` it's an error not warning and as you know it prevents actual flashing so that flag is mandatory for me

Yes. Originally ZEPPP would exit if trying to write outside the boundaries of your PIC. But then I started getting reports of people with HEX files that contained data beyond the boundaries, that tools generated with that extra padding, so I added a flag to make it just a warning.

> OK good to know because now we know that you did it thoroughly
You can post your HEX to a Gist if you want and I can check whether it's also just empty blocks in your case, but it most likely is.

> Edit: Can ZEPPP flash in HVP ?
Technically it shouldn't be that hard to make it HVP compatible. It would require adding an external supply or a boost converter. The communication protocol should remain largely unchanged, but some extra configuration checks might be needed. However that would defeat the purpose of being "Zero External Parts". Additional, an Arduino HVP programmer already exists (like the one you tried already).

EDIT: Made the answers more concise

**Comment by vido89** [comment]
> Here https://gist.github.com/vido89/6820e421f713f586401d8cd507fe4458 you can check it, thanks 

Sorry for taking this long to reply, @vido89  I just had the chance to review this. 
Well I'm glad that we went through the process of checking your HEX. Turns out that this time this might actually be a bug in ZEPPP. The 16F88x family seems to have **two** configuration words, and the second one should be mapped to 0x4010 (byte-based location) and currently ZEPPP wrongly assumes that the 16F88X processors only has **one** configuration word, making that address "out of bounds". Now, the second configuration word only covers Write-protection bits and the brown-out voltage, so ignoring it is not a huge issue for most applications.

Having said that, this should be corrected.
The fix is easy; It's just fixing the parameters for the 16F88x processors, but I'd love to be able to test it first before deploying a new version, and that could take a bit.

So if you don't mind waiting a little bit, know in the meantime that ZEPPP is ignoring the second CONF word. Now,  I could also upload a "dev" branch with the fix for you to test, if you prefer (and have the time to test it).

**Comment by vido89** [comment]
No worries @battlecoder, sorry for late reply I just now realized that you reply, so Im glad that you figure out what is wrong sure I'm glad to be tester

**Comment by battlecoder** [comment]
> No worries [@battlecoder](https://github.com/battlecoder), sorry for late reply I just now realized that you reply, so Im glad that you figure out what is wrong sure I'm glad to be tester

Great, I'll let you know once I have a dev branch. In the meantime I opened a new issue to keep track of this, without derailing this one: [https://github.com/battlecoder/zeppp/issues/15](https://github.com/battlecoder/zeppp/issues/15) . Let's continue there.
