### ISSUE TITLE
ZEPPP - Without the computer?

### ISSUE THREAD

**Issue by mdeweerd** [battlecoder/zeppp#4]
Maybe you're not to far away from a stand-alone programmer.

The Pickit2 has a mode where the program can be loaded in Pickit2 which can then work without the computer and program pics with a push on the button.

If the hex file could be include in some way in the program itself, then the arduino would no longer require the CLI which is usefull for independent programming or in-circuit programming of a PIC from another controller.

**Comment by battlecoder** [comment]
Thanks for the detailed and quick response.
There's definitely a lot of boards and platforms under the "Arduino" umbrella. That's why I mentioned that there's probably boards out there where space or extra buttons/LEDs are already provided. As it stands now, there's nothing in ZEPPP specific to one "Arduino" platform, so I'm quite reluctant to add a feature that would only work in a subset of the supported boards (although I can't claim full compatibility with EVERY Arduino-compatible board. For starters, I suspect that 3.3V boards will not work with PICs that require ~5V for LVP).

I don't know if I'm reading your use-case scenario correctly, but I think I get the general idea.

Creating a C file with the "HEX" embedded in the code along with the configuration so you can include it at compile-time is definitely possible. This is a bit more "involved" and "static" than the way that PicKit's "Programmer to Go" mode works, and a lot less convenient, but from what you say it seems like it would cover your needs and would bypass the need for external memory.

I recommend you to check the **fw_commands.txt** file, as well as the functions that each command calls inside the firmware to get an idea of how the differences between PICs are handled.

I will keep thinking on this, though. I'm not discarding the feature, but I am yet to think of a way in which this could be added in a more general, less-static fashion. 

For the time being, I think I can help your experiments by isolating the PIC programming functions into its own file, separating them from the serial commands and wrapper methods. Would that be useful to you?

**Comment by mdeweerd** [comment]
I am not sure I will build on this project, I do not want you to spent too much effort on this.

Separating the functions is always a good idea as it is a step towards possibilities for other uses.  

Thank you for the pointers to the documents to read, first I'll have to check datasheets a bit further ;-).
