### ISSUE TITLE
PIC 16F887

### ISSUE THREAD

**Issue by Lexnrdx** [battlecoder/zeppp#6]
Hi, can you update your ZEPPP?
I'm interested to use a pic 16F887, a way modern one that supports much more different things.
thank you for all the work you have done until now.

**Comment by battlecoder** [comment]
Hey!
I'm always happy to add support for more microcontrollers, as long as they are at the very least LVP-compatible, which the 16F887 seems to be. I quickly checked the programming datasheet for the device, and it *looks* like I should be able to add support for it, provided I can get one PIC from the family.

Let me see if I can get one from local sources. If I have to order it online it may take a while, but I'm on the case.

If you are willing to test as well let me know.

Regards!

**Comment by battlecoder** [comment]
Hi @Lexnrdx !
I received a couple of 16F887 devices two days ago, and I created a branch to work on supporting those devices: [experimental/PIC16F88X](https://github.com/battlecoder/zeppp/tree/experimental/PIC16F88X)

I did some quick tests tonight, and seems to be working fine, except for a few things that can be improved:

- Reading and writing to PGM is working, but it's using the slowest algorithm instead of taking advantage of the block-write capabilities of this family of PICs. I may need to implement that to speedup the PGM memory operations.
- Calibration data is not implemented. Neither reading nor writing.

None of the "issues" above are critical, and you should be able to program your device with what I managed to get working.
Please test that branch if you can. You don't need to compile the source code. I updated the [jar in the experimental branch](https://github.com/battlecoder/zeppp/blob/experimental/PIC16F88X/zeppp-cli.jar), so it should be a drop-in replacement to the current version of ZEPPP-CLI, and should work out of the box with the 16F887.

Let me know if it works for you.

**Comment by battlecoder** [comment]
This has been merged into the master branch. None of the potential improvements for this implementation were critical, and all the main programming functions seem to work as expected.
